name: FT-integration
on:
  workflow_dispatch:
    inputs:
      testPaths:
        description: 'Test path(s)' # "path\to\folder" or "path\to\GUITest1" or array of paths: ["path\\to\\GUITest1", "path\\to\\GUITest2", ...]. Absolute paths are not allowed. The paths will be validated against the repository root.
        required: true
        default: ""
permissions:
  contents: read  # Retain read access to contents if needed
#  actions: read  # Explicitly grant actions:read for this workflow
env:
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    ACTIONS_STEP_DEBUG: true  # Enables debug logging
jobs:
  ft_integration_job:
    runs-on: [self-hosted]
    name: Integration-Job
    steps:
      - name: FT Integration
        uses: dorin7bogdan/functional-testing@latest
        id: ft-integration
        with:
          testPaths: ${{inputs.testPaths}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          archiveReportsAsSingleArtifact: false
          logLevel: 3
          cleanupTestRunFiles: false
          ftlUrl: https://raw.githubusercontent.com/dorin7bogdan/tools/main/FTToolsLauncher_26.3.exe
