name: GitHub-Action-FT-Integration
on:
  workflow_dispatch:
env: 
    NODE_TLS_REJECT_UNAUTHORIZED: 0
jobs:
  ft_integration_job:
    runs-on: self-hosted
    name: Integration-Job
    steps:
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Ensures Node20 is available
          
      - name: GitHub Action FT Integration
        uses: dorin7bogdan/github-action-ft-integration@main
        id: gha-ft-integration
        with:
          octaneUrl: 'https://qa8.almoctane.com'
          octaneSharedSpace: 128004
          octaneWorkspace: 2001
          octaneClientId: ${{secrets.OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.OCTANE_CLIENT_SECRET}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          #serverBaseUrl: ${{ github.server_url }}/${{ github.repository }}.git
