name: GitHub-Action-FT-Integration
on:
  workflow_dispatch:
#    inputs:
#      testing-tool-type:
#        description: 'UFT or MBT'
#        default: MBT
#        type: choice
#        options:
#        - UFT
#        - MBT
  push:
    branches:
      - main
permissions:
  actions: read  # Explicitly grant actions:read for this workflow
  contents: read  # Retain read access to contents if needed
env: 
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    ACTIONS_STEP_DEBUG: true  # Enables debug logging
jobs:
  ft_integration_job:
    runs-on: self-hosted
    name: Integration-Job
    steps:
      - name: GitHub Action FT Integration
        uses: dorin7bogdan/github-action-ft-integration@main
        id: gha-ft-integration
        with:
          octaneUrl: 'https://integration-master-dev.almoctane.com'
          octaneSharedSpace: 2002
          octaneWorkspace: 2002
          octaneClientId: ${{secrets.OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.OCTANE_CLIENT_SECRET}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          minSyncInterval: 15
          logLevel: 2          
