name: GitHub-Action-FT-Integration
on:
  workflow_dispatch:
    inputs:
      testing-tool-type:
        description: 'UFT or MBT'
        default: UFT
        type: choice
        options:
        - UFT
        - MBT
  push:
    branches:
      - main
env: 
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    ACTIONS_STEP_DEBUG: true  # Enables debug logging
jobs:
  ft_integration_job:
    runs-on: self-hosted
    name: Integration-Job
    steps:
      - name: GitHub Action FT Integration
        uses: dorin7bogdan/github-action-ft-integration@main
        id: gha-ft-integration
        with:
          octaneUrl: 'https://qa8.almoctane.com'
          octaneSharedSpace: 128004
          octaneWorkspace: 2001
          octaneClientId: ${{secrets.OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.OCTANE_CLIENT_SECRET}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          logLevel: 2
          testingToolType: ${{inputs.testing-tool-type}}
          #serverBaseUrl: ${{ github.server_url }}/${{ github.repository }}.git
